<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Category;
use App\Models\Writer;
use Illuminate\Database\Seeder;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'category' => 'novels',
                'title' => 'الفيل الأزرق',
                'slug' => 'blue-elephant',
                'writer' => 'ahmed-mourad',
                'description_short' => 'يحيى الراوي، طبيب تخدير يعود إلى مستشفى العباسية للأمراض النفسية بعد غياب خمس سنوات، ليجد نفسه في مواجهة قضية غامضة تتشابك فيها حدود الواقع والجنون.',
                'pages_count' => 320,
                'published_year' => 2012,
                'file_size_mb' => 4.2,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['إثارة', 'غموض', 'نفسي', 'أدب عربي معاصر'],
                'downloads_count' => 18540,
                'rating_average' => 4.5,
                'rating_count' => 2340,
            ],
            [
                'category' => 'novels',
                'title' => 'يوتوبيا',
                'slug' => 'utopia',
                'writer' => 'ahmed-khaled-tawfik',
                'description_short' => 'رواية ديستوبية تدور أحداثها في مصر عام 2023، حيث ينقسم المجتمع إلى طبقة ثرية معزولة وأغلبية تعيش في فقر مدقع.',
                'pages_count' => 216,
                'published_year' => 2008,
                'file_size_mb' => 3.1,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['ديستوبيا', 'خيال علمي', 'أدب عربي معاصر'],
                'downloads_count' => 17800,
                'rating_average' => 4.5,
                'rating_count' => 1980,
            ],
            [
                'category' => 'novels',
                'title' => 'أرض زيكولا',
                'slug' => 'zikola-land',
                'writer' => 'amr-abdelhamid',
                'description_short' => 'رحلة غامضة تتشابك فيها عوالم موازية وأسرار مدفونة، في واحدة من أكثر الروايات العربية إثارة وتشويقًا.',
                'cover_image' => 'assets/books/zikola-land.jpeg',
                'pages_count' => 480,
                'published_year' => 2019,
                'file_size_mb' => 5.6,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['إثارة', 'غموض', 'خيال'],
                'downloads_count' => 22000,
                'rating_average' => 4.8,
                'rating_count' => 3010,
            ],
            [
                'category' => 'novels',
                'title' => 'فيرتيجو',
                'slug' => 'vertigo',
                'writer' => 'ahmed-mourad',
                'description_short' => 'مصور فوتوغرافي يجد نفسه شاهدًا على جريمة قتل غامضة في ملهى ليلي، لتبدأ رحلة بحث عن الحقيقة وسط الفساد والسلطة.',
                'pages_count' => 280,
                'published_year' => 2010,
                'file_size_mb' => 3.6,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['إثارة', 'جريمة'],
                'downloads_count' => 11000,
                'rating_average' => 4.4,
                'rating_count' => 1420,
            ],
            [
                'category' => 'novels',
                'title' => 'تراب الماس',
                'slug' => 'turab-al-mas',
                'writer' => 'ahmed-mourad',
                'description_short' => 'صيدلي بسيط يرث وصفة كيميائية غامضة تقوده إلى عالم من المؤامرات والصراع على السلطة في القاهرة.',
                'pages_count' => 300,
                'published_year' => 2011,
                'file_size_mb' => 3.9,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['إثارة', 'مغامرة'],
                'downloads_count' => 13400,
                'rating_average' => 4.6,
                'rating_count' => 1650,
            ],
            [
                'category' => 'arabic-literature',
                'title' => 'عزازيل',
                'slug' => 'azazeel',
                'writer' => 'youssef-ziedan',
                'description_short' => 'مخطوطة راهب مصري في القرن الخامس الميلادي، تروي صراعه الداخلي بين الإيمان والشك عبر رحلته بين مصر والشام.',
                'pages_count' => 356,
                'published_year' => 2008,
                'file_size_mb' => 4.4,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['تاريخي', 'فلسفي', 'أدب عربي'],
                'downloads_count' => 15200,
                'rating_average' => 4.6,
                'rating_count' => 2010,
            ],
            [
                'category' => 'arabic-literature',
                'title' => 'موسم الهجرة إلى الشمال',
                'slug' => 'season-of-migration-to-the-north',
                'writer' => 'tayeb-salih',
                'description_short' => 'من أهم روايات الأدب العربي الحديث، تتناول الصدام الثقافي بين الشرق والغرب من خلال قصة عودة مصطفى سعيد إلى قريته السودانية.',
                'pages_count' => 240,
                'published_year' => 1966,
                'file_size_mb' => 2.9,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['أدب عربي كلاسيكي', 'اجتماعي'],
                'downloads_count' => 12300,
                'rating_average' => 4.7,
                'rating_count' => 1740,
            ],
            [
                'category' => 'arabic-literature',
                'title' => 'رجال في الشمس',
                'slug' => 'men-in-the-sun',
                'writer' => 'ghassan-kanafani',
                'description_short' => 'رواية قصيرة مؤثرة تروي محاولة ثلاثة لاجئين فلسطينيين عبور الحدود إلى الكويت بحثًا عن حياة كريمة.',
                'pages_count' => 96,
                'published_year' => 1963,
                'file_size_mb' => 1.6,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['أدب عربي كلاسيكي', 'قصة قصيرة'],
                'downloads_count' => 9800,
                'rating_average' => 4.5,
                'rating_count' => 1120,
            ],
            [
                'category' => 'world-literature',
                'title' => 'الخيميائي',
                'slug' => 'the-alchemist',
                'writer' => 'paulo-coelho',
                'description_short' => 'راعي غنم إسباني ينطلق في رحلة بحثًا عن كنز دفين، ليكتشف أن أعظم كنز هو رحلة اكتشافه لذاته.',
                'cover_image' => 'assets/books/alchemist.jpeg',
                'pages_count' => 208,
                'published_year' => 1988,
                'file_size_mb' => 2.7,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['فلسفي', 'رمزي', 'أدب عالمي'],
                'downloads_count' => 21000,
                'rating_average' => 4.6,
                'rating_count' => 2870,
            ],
            [
                'category' => 'world-literature',
                'title' => 'مئة عام من العزلة',
                'slug' => 'one-hundred-years-of-solitude',
                'writer' => 'gabriel-garcia-marquez',
                'description_short' => 'ملحمة أسرة بوينديا عبر سبعة أجيال في قرية ماكوندو الخيالية، تحفة الواقعية السحرية في الأدب اللاتيني.',
                'cover_image' => 'assets/books/100_years_alone.jpg',
                'pages_count' => 432,
                'published_year' => 1967,
                'file_size_mb' => 5.1,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['واقعية سحرية', 'أدب عالمي'],
                'downloads_count' => 19500,
                'rating_average' => 4.7,
                'rating_count' => 2530,
            ],
            [
                'category' => 'world-literature',
                'title' => '1984',
                'slug' => '1984',
                'writer' => 'george-orwell',
                'description_short' => 'رواية ديستوبية كلاسيكية تصور مجتمعًا شموليًا تحت مراقبة "الأخ الأكبر"، من أهم أعمال القرن العشرين.',
                'pages_count' => 328,
                'published_year' => 1949,
                'file_size_mb' => 3.4,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['ديستوبيا', 'خيال علمي', 'أدب عالمي'],
                'downloads_count' => 14500,
                'rating_average' => 4.8,
                'rating_count' => 3120,
            ],
            [
                'category' => 'world-literature',
                'title' => 'الأمير الصغير',
                'slug' => 'the-little-prince',
                'writer' => 'antoine-de-saint-exupery',
                'description_short' => 'حكاية شاعرية عن أمير صغير يسافر بين الكواكب، تحمل تأملات عميقة عن الحب والصداقة ومعنى الحياة.',
                'pages_count' => 96,
                'published_year' => 1943,
                'file_size_mb' => 1.8,
                'formats' => ['PDF', 'EPUB'],
                'tags' => ['خيال', 'فلسفي', 'أدب عالمي'],
                'downloads_count' => 16700,
                'rating_average' => 4.9,
                'rating_count' => 2210,
            ],
        ];

        foreach ($books as $book) {
            $categoryId = Category::where('slug', $book['category'])->value('id');
            $writerId = Writer::where('slug', $book['writer'])->value('id');
            unset($book['category'], $book['writer']);

            Book::updateOrCreate(
                ['slug' => $book['slug']],
                $book + ['category_id' => $categoryId, 'writer_id' => $writerId]
            );
        }
    }
}
