<?php

if (! function_exists('asset_min')) {
    /**
     * Cache-busted asset URL that serves the minified .min.css/.min.js
     * counterpart in production (generated by `php artisan assets:minify`),
     * falling back to the original file everywhere else — so local edits to
     * a .css/.js file always show up immediately with no build step.
     */
    function asset_min(string $relativePath): string
    {
        $minPath = preg_replace('/\.(css|js)$/', '.min.$1', $relativePath);

        $path = (app()->environment('production') && file_exists(public_path($minPath)))
            ? $minPath
            : $relativePath;

        return asset($path).'?v='.filemtime(public_path($path));
    }
}
