<?php

if (! function_exists('asset_min')) {
    /**
     * Cache-busted asset URL that serves the minified .min.css/.min.js
     * counterpart in production (generated by `php artisan assets:minify`),
     * falling back to the original file everywhere else — so local edits to
     * a .css/.js file always show up immediately with no build step.
     */
    function asset_min(string $relativePath): string
    {
        $minPath = preg_replace('/\.(css|js)$/', '.min.$1', $relativePath);

        $path = (app()->environment('production') && file_exists(public_path($minPath)))
            ? $minPath
            : $relativePath;

        return asset($path).'?v='.filemtime(public_path($path));
    }
}

if (! function_exists('force_https_url')) {
    /**
     * Upgrades a stored http:// URL to https:// everywhere except local dev,
     * where nothing actually serves HTTPS (APP_URL is plain http://localhost)
     * — forcing it there just breaks every uploaded cover/photo/file link.
     */
    function force_https_url(string $value): string
    {
        if (app()->environment('local')) {
            return $value;
        }

        return str_starts_with($value, 'http://') ? 'https://'.substr($value, strlen('http://')) : $value;
    }
}
